### ISSUE TITLE
[Issue] VSSTester.ps1 does not check for updates when starting

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#1030]
When using SetupAssist and HealthChecker script, they both do search for updates when starting up. Is it true that this does NOT happen with VSSTester.ps1? Or is there something wrong with my machine?

If so, can this be added, please? It should be added to all the scripts...

**Comment by dpaulson45** [comment]
VSSTester.ps1 does not have the code to check for updates. We only have that for scripts that have frequent updates. Like the SetupAssist and HealthChecker.

**Comment by worldsdream** [comment]
It would be great if all these scripts had such functionality and checked for updates. Perhaps one day, this can be added if this is not a big request to ask for.

**Comment by dpaulson45** [comment]
It isn't a big ask, due to the way we wrote out the shared code to be easily added to scripts, but it likely wouldn't need to be added to all the scripts. That is where we would need to decide that, as it really isn't needed for all the scripts. 

For example, Clear-MailboxPermissions.ps1 or Find-AmbiguousSids.ps1 are pretty simple and easy scripts that haven't been modified since they have been added to the repository. They are also niche type scripts that you should only be using once in a long while. This would be similar to VSSTester, you should only be using it as a testing tool when you have backup issues. Typically, then we would suspect that the script would get removed or deleted after so long time has passed after resolving their issue. Then if they need to use the script again, they will want to download it again. 

Do you have a scenario in mind that could help explain why VSSTester for example would benefit from the update?

@bill-long  thoughts on this?

**Comment by worldsdream** [comment]
VSSTester didn't work with non-English systems and an update was released for it. Every time the engineer was opening the file, he got an error and was troubleshooting why this happens. Without knowing that there was an update that fixes the bug.

This is just one simple reason. But a reason that the script did not work eventually which is a bummer at that time.

Most don't know that there is a Github page and that there are fixes pushed to these scripts.

**Comment by bill-long** [comment]
There are a few interesting points here.

* Whether a script checks for updates is not really visible to the user unless there's an update. Maybe this isn't always the right approach. We might want to consider a parameter that makes the update check provide more feedback. "Latest version is nn.nn, no update needed", etc, just to indicate to the user that a check happened. We already have another issue opened about making auto update failures more visible, at least as an option, so we can tackle that at the same time.
* We might want to add additional behavior options to the shared auto-update code. Right now, your choices are update, or don't. But maybe for some scripts, we just want to tell the user that an update is available, and here's where they can download it.
* We might want to consider raising awareness of the GitHub repo even without auto-update. For example, maybe scripts should point to their docs URL when they finish, or something like that.

I think the aggressive self-overwrite behavior of HealthChecker and SetupAssist is appropriate for those scripts, but I'm not sure we should add that exact behavior to every script. If we have more flexibility on what the auto-update code can do, though, we can plug it into a lot more of the scripts.

**Comment by dpaulson45** [comment]
Closing issue, VSSTester.ps1 now has the code to check for updates. If other scripts require this, or we want to make a work item, let's create a new issue for that.

**Comment by worldsdream** [comment]
@dpaulson45 this helps a LOT. Thanks!!
