### ISSUE TITLE
[Issue] - Health Checker - SU install status on Exchange 2013 CU23

### ISSUE THREAD

**Issue by CommanderDOS** [microsoft/CSS-Exchange#1074]
Health Checker script version 22.05.20.1132

In an Exchange 2013 CU23 DAG of 2 machines, where the latest May-2022 security update was not installed, both machines shown as vulnerable with the Health Checker script. So good, so far.

After 1 of the 2 machines got the latest SU installed and the "Setup.exe /IAcceptExchangeServerLicenseTerms /PrepareAllDomains" command was executed, both machines shown as fully patched and non vulnerable. Even on the second machine which does not have the latest SU installed yet. I assume this is related to the Health Checker script itself and I will install the latest SU also on the second machine.

Health Checker script result on the machine where the May-SU is not installed: _All known security issues in this version of the script passed._

**Comment by dpaulson45** [comment]
This is to be expected. Besides fixes from previous SUs that caused regressions that were addressed, the CVE-2022-21978 is a domain level permission fix. Once you run `.\Setup.exe /IAcceptExchangeServerLicenseTerms /PerpareAllDomains` it protects you against that CVE in your environment. Therefore, the SU is not required to be installed on all your machines in the environment to protect against this CVE, but highly recommended to be at the same level and to get the other fixes that were included in it.

**Comment by CommanderDOS** [comment]
Thank you for the explanation. This know make sense to me. So when I understood correctly, the May-2022 SU dont need to be installed on the second Exchange server manually, as all previous updates/patches have been installed on the machine and for the May-2022 SU it got covered already by the "Setup.exe /IAcceptExchangeServerLicenseTerms /PrepareAllDomains" command run on the first machine? So the Health Checker script show the vulnerability status as expected?

**Comment by dpaulson45** [comment]
Correct for the [CVE-2022-21978[(https://msrc.microsoft.com/update-guide/vulnerability/CVE-2022-21978), you were protected from it once you ran the `/PrepareAllDomains` cmdlet. You are not required to install that SU on the second server to protect against that CVE and run the cmdlet again because it has already been done. However, it is recommended to be on the same build of Exchange on all the servers within a DAG. Plus, there were other fixes other than just the CVE fix that was included in this SU release.
