### ISSUE TITLE
[Issue] Healthchecker warning about BITS not running

### ISSUE THREAD

**Issue by hapklaar** [microsoft/CSS-Exchange#1215]
Our Windows 2016 servers running Exchange 2016 automatically change the startup type for BITS to manual from auto-start (delayed) every 30 minutes and then back again.

```
- 07:00:35 The Windows Update service entered the running state.
- 07:05:42 The start type of the Background Intelligent Transfer Service service was changed from demand start to auto start.
- 07:05:42 The Background Intelligent Transfer Service service entered the running state.
```
2 minutes later:
```
- 07:07:44 The start type of the Background Intelligent Transfer Service service was changed from auto start to demand start.
- 07:07:44 The Background Intelligent Transfer Service service entered the stopped state.
- 07:24:26 The Windows Update service entered the stopped state.
```
This seems to be driven by Windows Update being started every 30 minutes, 5 minutes prior to the BITS service change and then stopped some 15 minutes after.

This causes the following warning to appear in the HealthChecker output when it is run on an off cycle:
```
        Common Services Not Running:
                BITS - Status: Stopped - StartType: Manual
```

I don't know what causes this service behavior, could be SCOM, but it seems to be by design. Should this warning be in HealthChecker?

**Comment by dpaulson45** [comment]
Not sure if it should be set to `Manual` but I do have a lab where it is set that way on 2016 and another that doesn't have it set to manual.

@lusassl-msft should we still display if this service isn't running when set to `Manual`? This is what I am currently thinking: 

- Any critical services that should be set to `automatic` that is set to `manual` should be flagged as an issue
- Any critical services that isn't running should be flagged as an issue, even if set to `manual` for a startup type (aka: Pla is a manual critical service) 
- Any common service that should be set to `automatic` that is set to `manual` should be flagged as a warning
- Any common service that should be running that is **NOT** set to `manual` for a startup type, should be flagged as a warning (aka BITS - only concern would be is if we have an issue with OAB downloads caused by the service being set to `manual` and not starting)

**Comment by hapklaar** [comment]
@dpaulson45 The service continuously changes from automatic to manual. This is probably why you observed different states on different environments. Healthchecker reporting on BITS being on manual seems unnecessary in that context.

**Comment by lusassl-msft** [comment]
@dpaulson45 what about this for the BITS: Validate that the service is not set to disabled. If it is set to automatic, automatic [delayed] or manual this should be okay and we should not highlight (even if the service is stopped as this can also happen from time to time for some reason).

**Comment by dpaulson45** [comment]
@lusassl-msft that is what I have basically coded out. You can check it out in the PR.
