### ISSUE TITLE
Health Checker -ScriptUpdateOnly asking for prompt to confirm

### ISSUE THREAD

**Issue by docbitter** [microsoft/CSS-Exchange#1317]
**Provide Version Number**
Health Checker version 22.11.02.1803

**Describe the issue**
.\HealthChecker.ps1 -ScriptUpdateOnly
Checks for update but asks user for confirmation to acutally do the update

**Expected behavior**
.\HealthChecker.ps1 -ScriptUpdateOnly should do a silent update without user interaction

**Script Output**
.\HealthChecker.ps1 -ScriptUpdateOnly

Bestätigung
Möchten Sie diese Aktion wirklich ausführen?
Ausführen des Vorgangs "Update script to latest version" für das Ziel "HealthChecker.ps1".
[J] Ja  [A] Ja, alle  [N] Nein  [K] Nein, keine  [H] Anhalten  [?] Hilfe (Standard ist "J"):
File signed by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
AutoUpdate: Signature validated.
AutoUpdate: Succeeded.
Script was updated. Please rerun the command.

**Additional context**
We use the script to generate a daily health report of our exchange environment and mail this to a team. Whenever the script gets updated the Task is stuck at a hidden confirmation. We are looking for a way to do a silent update.

**Comment by dpaulson45** [comment]
@docbitter I believe this must be something on your system. I just went ahead and downloaded an older version and did `.\HealthChecker.ps1 -ScriptUpdateOnly` and it downloaded the latest update and didn't prompt me. Proceed to do the same for the latest version, no prompt. 

![image](https://user-images.githubusercontent.com/22776718/199725199-f611fa21-6fb5-4107-91c7-992e01d80018.png)

What version of the script did you have when you were using that switch. There was an issue a while back regarding this, but it shouldn't be present any longer.

**Comment by bill-long** [comment]
This may also depend on whether you trust the Microsoft certificate and/or the execution policy. In addition, I think -Confirm:$false would prevent the prompt.

**Comment by docbitter** [comment]
Thanks David! When i add the line 
Set-ExecutionPolicy RemoteSigned to my script the prompt is gone

**Comment by bill-long** [comment]
@docbitter Are you sure you're not confusing the execution prompt and the update prompt?

There are two possible prompts as shown in this screenshot:

![image](https://user-images.githubusercontent.com/4518572/200313452-da698c6a-49af-46d3-9a62-a8286536065e.png)

Adding `-ScriptUpdateOnly` stops the update prompt because we pass `-Confirm:$false` in that case:

![image](https://user-images.githubusercontent.com/4518572/200313814-0c499837-e435-4563-a3ca-b53b49400338.png)

Note how -ScriptUpdateOnly stops the update prompt, but not the execution prompt:

![image](https://user-images.githubusercontent.com/4518572/200315009-e8956f2f-ac09-44cb-a316-275c3d425ae9.png)

You can also disable the update prompt without -ScriptUpdateOnly by adding -Confirm:$false. Note how in the following screenshot, I still receive the execution prompt, but not the update prompt:

![image](https://user-images.githubusercontent.com/4518572/200314018-3162fa28-9712-4b86-bbdb-02f9edd119f1.png)

Execution policy shouldn't have any effect on the update prompt, but it might affect the execution prompt. Typically you can stop the execution prompt by unblocking the file:

![image](https://user-images.githubusercontent.com/4518572/200316640-6f92d71d-29e4-489b-ab6b-708bbf50f89e.png)

In fact, editing the script as you described should make it fail to run under a RemoteSigned policy unless the script is unblocked:

![image](https://user-images.githubusercontent.com/4518572/200317123-5a0be332-a096-418a-8b7a-5816e9ae8d22.png)

**Comment by bill-long** [comment]
@dpaulson45 Yeah, but execution policy would not affect that. His last post was:

    Thanks David! When i add the line
    Set-ExecutionPolicy RemoteSigned to my script the prompt is gone

That does not make any sense in context of the original post.

**Comment by docbitter** [comment]
Hi David, Hi Bill,

you are both right. I confused the execution prompt and the update prompt. The execution prompt is gone since i added the Execution Policy to the script.

BUT now i cannot reproduce the issue. The script updates itself now right away.

a) I got an "Update Script to the latest version?"-Prompt when I executed the script without any switches. 
b) I got an "Update Script to the latest version?"-Prompt when I executed the script with the "-ScriptUpdateOnly" switch
-> b) is the reason i started this question.

Now i don´t get any prompt whatever switch i use.

![2022-11-07 16_28_14-10 249 9 123 - Remotedesktopverbindung](https://user-images.githubusercontent.com/117347856/200349277-2fac2d20-1411-47f3-94bf-b4ed1d92aae8.png)

![2022-11-07 16_31_56-10 249 9 123 - Remotedesktopverbindung](https://user-images.githubusercontent.com/117347856/200350039-d1f7c0a7-72cd-42f6-af4e-f7d788b89885.png)

**Comment by dpaulson45** [comment]
@docbitter I wonder if you were on an older build of Health Checker where this was still a problem and was resolved within that old issue I provided above.

Since you are no longer seeing the issue with the update piece, then I think it is safe to say that we can close out this issue.

**Comment by docbitter** [comment]
Thanks David, yes: we close out this.
