### ISSUE TITLE
[Issue] - Health Checker - EWS InternalNLBBypassUrl lacks any details causing confusion

### ISSUE THREAD

**Issue by colinSubscriptionEdition** [microsoft/CSS-Exchange#1659]
**Provide Version Number**
All versions
**Provide the version of the script that has the issue.**
EWS InternalNLBBypassUrl gives an error stating "Can cause issues after KB 5001779".  There are no details on this.  I've opened support cases and havn't found anyone in MS Support who is aware of the issue.  

**Describe the issue**
Need more details on the actual issue.  What issues occur after the KB if an EWS bypass url is used.  Is it an ews issue? 

**Expected behavior**
Would expect a link to an article or significant details - at least something more than "can cause issues".  The MS Support reps I've spoken with would appreciate more information here as well.  Is there an issue?  If so, how is the bypass URL causing the issue?  What would we expect if we remove the bypass URL?

**Comment by dpaulson45** [comment]
This issue is due to #595 

`InternalNLBBypassUrl` isn't required any more in Exchange 2013 because of the changes that were made. This setting was primarily for keeping session affinity working when we had 2010 or lower CAS servers trying to talk to CAS servers in a different site as we couldn't talk to the mailbox servers directly. Now, we talk to the mailbox servers directly and there isn't an AD boundary limit like there once was. There is no need to have this set any longer for the FE of EWS as it only causes problems that we have seen.

**Comment by dpaulson45** [comment]
It is there by default if you installed 2013+ in its own environment. This is there from the objects from 2010 with client access arrays we auto set it.

**Comment by colinSubscriptionEdition** [comment]
Thanks for the information.
And to clarify one last thing...

You are only talking about the bypass url for the frontend, correct?  Or the backend as well?


Get-WebServicesVirtualDirectory -Server servername -ShowMailboxVirtualDirectories | Select Name, *URL* | FT -AutoSize

Name
----
**EWS (Exchange Back End)** https://servername:444/ews/exchange.asmx
**EWS (Default Web Site)**  https://servername/ews/exchange.asmx

**Comment by dpaulson45** [comment]
@colinSubscriptionEdition This would be only the Front End where the URL should not be set, which is the case for a fresh environment.

The BE we do use, and it should always be the default value of FQDN:444.
