### ISSUE TITLE
Add a reference to ConfigureCryptoDefaults.ps1 script for E19 in the TLS section of HealthChecker

### ISSUE THREAD

**Issue by gabymuntean** [microsoft/CSS-Exchange#1711]
I have recently got an issue with incorrect TLS configuration set by Nartac IISCrypto tool.
I was not aware of the ConfigureCryptoDefaults.ps1 script (that is available with E19 in the $ExInstall\Bin folder) which can easily be used to setup a more secure or more relaxed cipher suites list and configure correctly the other TLS settings, as we recommend.

**Comment by dpaulson45** [comment]
@gabymuntean  what is the ask here? To throw a warning if E19 isn't configured any longer out of the box from setup?

**Comment by dpaulson45** [comment]
Not sure if a call out stating this as a note every time would be beneficial, even against a 2019 Exchange Server. Some customers might have a reason to not disable TLS 1.0/1.1 for home grown applications and they needed to remove what we set to be the most secure for a time.

**Comment by dpaulson45** [comment]
@gabymuntean need to know what the other keys are related to TLS that we might want to include that we don't yet already. 

I don't believe it is wise to include a reference to the script regarding how to configure TLS, just because of the mixed environments deal. We don't even run the `ConfigureCryptoDefault.ps1` between CU build upgrades because of it messing with TLS that might have been there for a reason within the customer environment. Then depending on which CU they have installed, will depend on what all gets done and changed. So, if there was a mixed version of CUs, that could have different results which will not have the desired outcome.

**Comment by lusassl-msft** [comment]
@gabymuntean we discussed this internally and decided that we don’t want to reference the script yet. We’ve refactored the TLS documentation and replaced the more complex registry configuration steps with copy and paste PowerShell commands. The script itself was designed to run during setup and was not intended to run afterwards manually by customers. I will closely monitor the situation of TLS-related cases and we can re-open the discussion if we see a situation in which we should provide something for our customers.
