### ISSUE TITLE
[Issue] Running CompareExchangeHashes.ps1 gives error : baseline_15.1.1913.5.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it

### ISSUE THREAD

**Issue by lotfi213** [microsoft/CSS-Exchange#172]
Running CompareExchangeHashes.ps1 against Exchange 2016 CU15 installed in WS 2016 and a member of DAG of two nodes, 
gives the following error:

_baseline_15.1.1913.5.zip not found... please open issue on https://github.com/microsoft/CSS-Exchange/issues, we will work on it_

What should be done, please?

**Comment by 4lex11s** [comment]
Hello,
I have the same problem, because we use a proxy server... I think that the proxy test is missing in the script of microsoft :/
For my part, I solved it this way (in pwsh as admin):
`$(New-Object System.Net.WebClient).Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials 
.\CompareExchangeHashes.ps1`

same as:
`$b= New-Object System.Net.WebClient
$b.Proxy.Credentials =[System.Net.CredentialCache]::DefaultNetworkCredentials 
.\CompareExchangeHashes.ps1`


Regards

**Comment by anshuldube** [comment]
Can you please download the latest version of the script from: https://github.com/microsoft/CSS-Exchange/releases/latest/download/CompareExchangeHashes.ps1 and re-run.

**Comment by anshuldube** [comment]
This should be fixed now.
