### ISSUE TITLE
[Issue] - Health Checker Certificate Binding not containing Hostname.

### ISSUE THREAD

**Issue by blacks7** [microsoft/CSS-Exchange#1973]
**Provide Version Number**
24.01.23.1802

**Describe the issue**
Certificate Binding Issue Detected: 'XXXXXX' Exchange Back End does not have hostname or FQDN for the namespaces. This can cause connectivity issues.

On Line 4475

**Expected behavior**
After debugging we see an error on checking the if case:

 if ($namespaces -notcontains $exchangeInformation.GetExchangeServer.Fqdn -or
                            $namespaces -notcontains $exchangeInformation.GetExchangeServer.Name) {

we check the output for the variables:

$namespaces (variable output):  mail.int.domain.de mail.domain.de webmail.int.domain.de webmail.domain.de sync.domain.de ecp.int.domain.de ecp.domain.de ews.int.domain.de ews.domain.de oab.int.fhh-infra.de oab.domain.de mapi.int.domain.de mapi.domain.de autodiscover.domain.de autodiscover.int.domain.de smtp.int.domain.de pop3.int.domain.de imap.int.domain.de attachments.int.domain.de attachments.domain.de server1060.int.fhh-infra.de server1061.int.domain.de server1062.int.domain.de server1063.int.domain.de server1064.int.domain.de server1065.int.domain.de server1070.int.domain.de server1071.int.fhh-infra.de server1072.int.domain.de server1073.int.domain.de server1074.int.domain.de server1075.int.domain.de server1076.int.domain.de server1077.int.domain.de

$exchangeInformation.GetExchangeServer.Fqdn (variable output):  server1062.int.domain.de
$exchangeInformation.GetExchangeServer.Name (variable output):  server1062

**Script Output**
If applicable, add the exception that wasn't handled.

$problemCertList.Add("'$certHash' Exchange Back End does not have hostname or FQDN for the namespaces. This can cause connectivity issues.")

**Additional context**
you have to fix the condition from "-or" to "-and"

**Comment by dpaulson45** [comment]
Discussing internally to discuss with the possible wording/flag of issue.

The if statement is correct. We do expect **both** hostname & FQDN in the Backend bound certificate, just like out of the box Exchange Server with the self-signed certificate to avoid any possible issues.

**Comment by dpaulson45** [comment]
We ended up deciding to just remove this check, as there has been mixed results on what works and what doesn't. Since we don't have enough data to properly determine what scenarios where this is broken 100% of the time, we decided to remove the check. 

However, keep in mind that this is something that we have not tested and have documentation on how to do this on the Exchange Back End for different certs. Therefore, it is possible that future changes could change this from working to not working for various reasons and this will not be called out in our testing process.
