### ISSUE TITLE
ExchangeExtendedProtectionManagement.ps1 doesn't turn on PS SSL in Default Website

### ISSUE THREAD

**Issue by MercuryZXT** [microsoft/CSS-Exchange#2168]
When running the script it doesn't set this setting as it requires it to be. Then when running with -ShowExtendedProtection it shows this as an issue. I tried to run the script more than once on a few servers, problem remains and is visible in IIS management as well.
![image](https://github.com/user-attachments/assets/7374d859-af84-45e4-9dd9-69caf9d2fdd1)

**Comment by dpaulson45** [comment]
For starters, does the script actually run or just it just provides that this is a prerequisite problem that needs to be addressed before you can run the script? 

Secondly, PowerShell Default Front End doesn't have Extended Protection enabled on it and we don't set the SSL to be required there because it is NOT supported to use HTTPS on this connection to the FE. 

https://learn.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/security-best-practices/exchange-extended-protection?view=exchserver-2019#enabling-extended-protection

**Comment by MercuryZXT** [comment]
The script ran just fine and set almost everything required perfectly, just this setting was not changed, now whenever we run a EP test this comes back as an issue.

I would imagine the script should change this setting if it is required. Am I expected to change this specific setting manually for some reason? Or is it considered a pre requisite that I was meant to change before turning EP on? If so I don't remember seeing it in any documentation.

This is the output when running -ShowExtendedProtection after running the script, as you can see, all settings are correct, but this one isn't:
![image](https://github.com/user-attachments/assets/0742c0c4-8d64-4fbd-8f34-688b76f3ed61)

**Comment by dpaulson45** [comment]
@MercuryZXT All those settings are 100% correct. There is nothing wrong there. Again, PowerShell for the Default Web Site should not be forced to use SSL as that will break EMS and is not supported by Microsoft.

**Comment by MercuryZXT** [comment]
Then is the issue actually the EBE powershell? because the HealthChekcer script shows an error:
![image](https://github.com/user-attachments/assets/cb815717-a065-43ee-a5c2-1f6159010fdc)

Default Web Site is the one that caught my eye but perhaps I was wrong?
If this is indeed the case then I direct the question to this setting.

**Comment by dpaulson45** [comment]
Because you are using an old version of Health Checker script or Health Checker data. Please download the latest version and run the data collection again, then run the HTML report. https://aka.ms/ExchangeHealthChecker

We previously did set the Supported Value to `Require` when the script was first released. However, we couldn't set the SSL to Require. Because of this mismatch and the fact that we weren't really using the Auth Module, we then moved the Supported Value to `None` as there was no benefits to setting it.

**Comment by MercuryZXT** [comment]
I'll re-run the test with the new version and get back to you.

**Comment by dpaulson45** [comment]
Thanks for the feedback! Closing out the issue
