### ISSUE TITLE
[Issue] - Health Checker --ERROR-- Not enough logs to cover 7 days

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#2169]
**Provide Version Number**
Version 24.08.08.1523

**Describe the issue**
The report shows:

--ERROR-- Not enough logs to cover 7 days. Last log entry is at 08/09/2024 20:55:16. This could cause issues with determining Root Cause Analysis.

**Expected behavior**
It shouldn't show any errors because there are logs present.

Error in report:
![Error](https://github.com/user-attachments/assets/21b60be2-07d7-43f8-881a-e498493f79df)

Application log:
![Application](https://github.com/user-attachments/assets/9b000e1b-6d86-441b-bdcb-dcfd8c901f1d)

System log:
![System](https://github.com/user-attachments/assets/1b5242b5-3ae5-412d-8fb5-789ad2023b02)

**Comment by dpaulson45** [comment]
This test isn't for determining that there are logs present, but how far back they go. If you have an issue on a Friday, and don't open a case till Monday to assist with RCA, because of the amount of time that has already gone by in your environment only having a few days' worth of logs, that ends up being a problem.

**Comment by worldsdream** [comment]
It was not so clear to me. Now it does. Thanks @dpaulson45.
