### ISSUE TITLE
[Issue] CompareExchangeHashes.ps1 loading multiple baselines

### ISSUE THREAD

**Issue by ericwbentley** [microsoft/CSS-Exchange#220]
CompareExchangeHashes.ps1 version 21.03.10.0037 in release v21.03.10.0112

Looks like it's loading multiple baselines even though 15.1.2176.2 is detected

```
[03/09/2021 20:59:15] Started...
Found exchange version: 15.1.2176.2
Loaded baseline for 15.1.2044.8, hashes number 15237
Loaded baseline for 15.1.2044.12, hashes number 15237
Loaded baseline for 15.1.2044.4, hashes number 15175
Loaded baseline for 15.1.2176.9, hashes number 15237
Loaded baseline for 15.1.1531.3, hashes number 14653
Loaded baseline for 15.1.2176.2, hashes number 15237
Loaded baseline for 15.1.1979.3, hashes number 15174
BaselineData - 15.1.2044.8 15.1.2044.12 15.1.2044.4 15.1.2176.9 15.1.1531.3 15.1.2176.2 15.1.1979.3 15.1.2176.2
Processing 3 directories in parallel
```

This leads to .csv export with thousands of lines of NoHashMatch since it's comparing to multiple incorrect baselines

**Comment by ericwbentley** [comment]
Observing this also in the latest version 21.03.10.0536 in release v21.03.10.0544

**Comment by anshuldube** [comment]
> Observing this also in the latest version 21.03.10.0536 in release v21.03.10.0544

How does the result file look like?

**Comment by ericwbentley** [comment]
Just started the 21.03.10.0536 script so I will wait for the results and let you know.

The explanation makes sense, I wasn't sure if multiple baselines were expected. My concern then is if the script is checking against multiple baselines, if a file hash is matched in one baseline but not the others, will it still return the mismatches from the other baselines to the .csv?

For example, in my results from this morning, the same file is in the results 6 times. The script loaded 7 baselines, and I'm assuming the hash was matched to one baseline, but not the other 6.

https://i.imgur.com/IO85pdH.png

**Comment by psykokwak4** [comment]
> My concern then is if the script is checking against multiple baselines, if a file hash is matched in one baseline but not the others, will it still return the mismatches from the other baselines to the .csv?

currently (21.03.10.0544) this script does:
1. find all vdir physical paths
2. load all baseline data from csv, for the current [exchange install version](https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019), and possible versions installed in the past (e.g. the example versions shown above)
3. for a selected number of file types (https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L354), check if its hash is one of the loaded known good hashes
4. mark files modified after 12/01/2020 under `$env:SystemDrive\inetpub\wwwroot"`  as suspicious ([L335](https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L335), [L377](https://github.com/microsoft/CSS-Exchange/blob/d95e5e70a17a8baaa3661c507a32418f044091d5/Security/CompareExchangeHashes.ps1#L377))

multiple results shown in csv is caused by the fact (also current implementation) that some of the vdirs share the same physical path (for example, `Exchange Back End/owa/` and `Exchange Back End/owa/Calendar/`), it can be improved

the file shown as "NoHashMatch" (microsoft.o365.shellg2.core.js) is a known good file name, let us know if your local hash == hash found in baseline file ( `(get-content <one of the csv baseline files> | select-string -pattern '<hash>')`)
(or report issue if hash is not found)

**Comment by ericwbentley** [comment]
My results from 21.03.10.0536 returned a result .csv with 13798 lines. I do see that the same files are in the results multiple times with different VDirs as you mentioned.

I picked a random file from the results and tried to compare it's hash to the baselines downloaded and it was unable to match.

https://i.imgur.com/7E5JYC8.png

I notice there is a new column with "FileHash". Is this supposed to be the hash of the installed file or from the baseline? Because all the lines in the results file share the same 3 hashes or have no hash in that field.

https://i.imgur.com/I8JiCOq.png

If you want I can close this issue since multiple baselines are expected and the multiple lines issue seems to be a dupe of #170

**Comment by psykokwak4** [comment]
> My results from 21.03.10.0536 returned a result .csv with 13798 lines. I do see that the same files are in the results multiple times with different VDirs as you mentioned.
> 
> I picked a random file from the results and tried to compare it's hash to the baselines downloaded and it was unable to match.
> 
> https://i.imgur.com/7E5JYC8.png
> 
> I notice there is a new column with "FileHash". Is this supposed to be the hash of the installed file or from the baseline? Because all the lines in the results file share the same 3 hashes or have no hash in that field.
> 
> https://i.imgur.com/I8JiCOq.png
> 
> If you want I can close this issue since multiple baselines are expected and the multiple lines issue seems to be a dupe of #170

yes, it is, should be fixed in https://github.com/microsoft/CSS-Exchange/pull/252/files#diff-e7dece358b7dc77ad2f040a75fe2a65948bf8a4337df51cb643025bf81fe16f3R602
![image](https://user-images.githubusercontent.com/6261280/110700313-a8b53680-81a4-11eb-831b-05b8844feda0.png)

**Comment by psykokwak4** [comment]
we also need 15.1.1531.10 in VALID_VERSIONS

**Comment by anshuldube** [comment]
Created a single task for tracking all missing baselines, please follow: https://github.com/microsoft/CSS-Exchange/issues/313
