### ISSUE TITLE
[Issue] - Health Checker - Dynamic Memory Detected - Unknown - Required Counter not Loaded

### ISSUE THREAD

**Issue by worldsdream** [microsoft/CSS-Exchange#2256]
**Provide Version Number**
Exchange Health Checker v24.12.11.2250

**Describe the issue**
A warning message: Dynamic Memory Detected - Unknown - Required Counter not Loaded

**Expected behavior**
What do we have to do with this warning? There is no information about "Counter"? 

**Script Output**
See screenshot

![Image](https://github.com/user-attachments/assets/96cf298f-d075-4dfd-8e49-6f43672e376f)

**Comment by Grisu786** [comment]
Same Issue here, HealthChecker script claims dynamic ram is enabled - but it never was.

HealthChecker Warning:

![Image](https://github.com/user-attachments/assets/b950e53c-17b5-4467-a189-515dcfff02af)

Hyper-V Settings (showing dynamic ram is disabled)

![Image](https://github.com/user-attachments/assets/6ff5399a-1040-4e70-9981-bbb378b24594)

**Comment by dpaulson45** [comment]
@Grisu786 that issue is `unknown` because we aren't able to detect if dynamic memory is enabled or disabled because we couldn't find the required counter to determine this. If the counter isn't there, we will still report `unknown` and it will be up to the admin to check and/or correctly add the counter to the Exchange guest machine to properly have Health Checker determine this.

As you provided from your snapshot, you do not have it enabled. But the script will never be able to determine if the guest machine has this enabled or not if the counter isn't present.

**Comment by Grisu786** [comment]
@dpaulson45 Thanks for clarification 👍
