### ISSUE TITLE
Issue Test-proxyLogon.ps1 on Powershell 2.0

### ISSUE THREAD

**Issue by swissiws** [microsoft/CSS-Exchange#260]
Windows 2008 R2, Exchange 2010, Powershell 2.0

You must provide a value expression on the right-hand side of the '-' operator.
At C:\scripts\Test-ProxyLogon.ps1:228 char:48
+                             If ( $_.Extension - <<<< in $zipFilter ) {
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedValueExpression

**Comment by bill-long** [comment]
PowerShell 2 is not supported. It requires at least 3. Unfortunately it ignores the Requires directive since it isn't on the first line of the file.

Because Exchange 2010 is only vulnerable to CVE-2021-26857, the script only performs one of the tests from the blog:

Get-EventLog -LogName Application -Source "MSExchange Unified Messaging" -EntryType Error | Where-Object { $_.Message -like "*System.InvalidCastException*" }

You either run this manually, or you can enable PS Remoting and run the script from a different machine that has at least PowerShell 3.
