### ISSUE TITLE
Test-ProxyLogon.ps1: works not correctly on powershell lower than 3.0

### ISSUE THREAD

**Issue by RoseDeSable** [microsoft/CSS-Exchange#318]
The script shows this output:

#TYPE System.Collections.Hashtable
"IsReadOnly","IsFixedSize","IsSynchronized","Keys","Values","SyncRoot","Count"
"False","False","False","System.Collections.Hashtable+KeyCollection","System.Collections.Hashtable+ValueCollection","System.Object","4"
"False","False","False","System.Collections.Hashtable+KeyCollection","System.Collections.Hashtable+ValueCollection","System.Object","4"

I seems to be an incompatibilty with the new "PSCustomObject". Lower than version 3 it must be "New-Object -TypeName PSObject -Property". Exists the possibility to use the objects in according to the version of the powershell ?

**Comment by bill-long** [comment]
We actually have `#Requires -Version 3` in the script, but it gets ignored since older versions of PowerShell only recognize that if it's on the first line. Our 'fix' for this will likely to be change our build system so that `#Requires` can remain above the disclaimer. We do not plan to support lower versions of PowerShell.

That said, if you're trying to run this on version 2 I assume you're on Exchange 2010? Because Exchange 2010 is only vulnerable to CVE-2021-26857, the script only performs one of the tests from the blog:

`Get-EventLog -LogName Application -Source "MSExchange Unified Messaging" -EntryType Error | Where-Object { $_.Message -like "*System.InvalidCastException*" }`

You can either run this manually, or you can enable PS Remoting and run the script from a different machine that has at least PowerShell 3.

**Comment by bill-long** [comment]
Also started a FAQ that discusses running on Exchange 2010 and the PS version requirement: https://github.com/microsoft/CSS-Exchange/tree/bilong-faq/Security#frequently-asked-questions
