### ISSUE TITLE
baseline for malformed version 15.0.1497 missing

### ISSUE THREAD

**Issue by 7thsonch** [microsoft/CSS-Exchange#326]
On a 2013 system with CAS role installed (and no Mailbox role) where I run version 21.03.12.0437 of the script, 129 files are detected as malicious. As far as I understand, these are all files that were scanned at all (or at least in C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy). Among them are also files like C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\getidtoken.htm which contain only one line and are definitely not compromised.

Our environment has been running on 2013 CU23 for a while and has been updated several times in the past.  As far as I can see, only baseline_15.0.1497.2.zip was downloaded from the script.
Also special about our environment could be that we use Exchange 2013 and 2019 in mixed operation.

Extract from the csv file:
```
"LastAccessTimeUtc","PDir","FileName","LastWriteTimeUtc","Error","FileHash","FilePath","CreationTimeUtc","VDir"
"01/14/2020 09:00:00","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","fexppw.js","05/29/2019 00:02:58","NoHashMatch","A44CE1C6F389F6760F58229603BBD51D670FF7A6CE950BE7AE1BBF7F8DDC9477","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\scripts\premium\fexppw.js","05/29/2019 00:02:58","Default Web Site/owa/oma/"
"01/14/2020 09:00:00","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","flogon.js","05/29/2019 00:02:58","NoHashMatch","875B6F9260784AF34B387B2270EE3D6D8890DFF15EB16796819A2A18F5C40089","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\scripts\premium\flogon.js","05/29/2019 00:02:58","Default Web Site/owa/oma/"
"01/14/2020 09:00:01","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","errorFE.css","05/29/2019 00:02:58","NoHashMatch","CA58FBE25C8C3F90FA5E440215B039090D5A066AE03B52BD58B6159AC905F9AA","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\themes\resources\errorFE.css","05/29/2019 00:02:58","Default Web Site/owa/oma/"
"01/14/2020 09:00:01","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","logon.css","05/29/2019 00:02:58","NoHashMatch","2D2130A7D52C47ECE563218D148E6DAA726DCDF139A133F3F48C04FA661F4159","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\themes\resources\logon.css","05/29/2019 00:02:58","Default Web Site/owa/oma/"
"01/14/2020 09:00:01","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","owafont.css","05/29/2019 00:02:58","NoHashMatch","FE9FA734B49C7ECE6D93222A64FBE5FAD696CD5F93BFFA942F512964A0D148C6","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\themes\resources\owafont.css","05/29/2019 00:02:58","Default Web Site/owa/oma/"
"01/14/2020 09:00:01","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","owafont_ja.css","05/29/2019 00:02:58","NoHashMatch","8DDC6D2A3227A272F4F3F4D25BA01969E6DB869C928D64D8D6E14064019FF82B","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\15.0.1497\themes\resources\owafont_ja.css","05/29/2019 00:02:58","Default Web Site/owa/oma/"
[...]
"01/14/2020 08:59:47","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa","getidtoken.htm","05/29/2019 00:02:58","NoHashMatch","5E632C2EE54B9B2C22272334ACA7C1E55CA5129E65B24F226F8C51FDE832814E","C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\getidtoken.htm","05/29/2019 00:02:58","Default Web Site/owa/oma/"
[...]
```
```
[PS] C:\>Get-Date -Year "2020" -Month "12" -Day "01"
Tuesday, December 1, 2020 11:40:06 AM
```

**Comment by serpentes80** [comment]
Have the same issue

exchange 2019 CU8 SU installed

**Comment by psykokwak4** [comment]
we may need to map `15.0.1497` to version `15.0.1497.0`
will it help if you download baseline for 15.0.1497.0 manually, rename it (both zip file and csv file it contains) to 15.0.1497, add it to valid version directory (below), then rerun this script?
else we can copy and upload 15.0.1497.0 as 15.0.1497 baseline

https://github.com/microsoft/CSS-Exchange/blob/1c9607dfc7ab84b253efe0e4fcd7116cc09c1147/Security/src/CompareExchangeHashes.ps1#L130

C:\Program Files\Microsoft\Exchange Server\V15\FrontEnd\HttpProxy\owa\auth\ **15.0.1497**

**Comment by 7thsonch** [comment]
> will it help if you download baseline for 15.0.1497.0 manually, rename it (both zip file and csv file it contains) to 15.0.1497, add it to valid version directory (below), then rerun this script?

Yes, that worked. Thanks a lot!

**Comment by vboyev-MSFT** [comment]
Time stamps on the files are not a highly trusted piece of data. The attackers can modify the time stamps.

**Comment by psykokwak4** [comment]
> Time stamps on the files are not a highly trusted piece of data. The attackers can modify the time stamps.

change the regex to match non-IIS root files then, from

https://github.com/microsoft/CSS-Exchange/blob/1c9607dfc7ab84b253efe0e4fcd7116cc09c1147/Security/src/CompareExchangeHashes.ps1#L583

https://github.com/microsoft/CSS-Exchange/blob/1c9607dfc7ab84b253efe0e4fcd7116cc09c1147/Security/src/CompareExchangeHashes.ps1#L535

to something like:

```ps
New-Object System.Text.RegularExpressions.Regex -ArgumentList '(.+)\s+\"(.+)\"\s+\(physicalPath:(C:\\Program Files\\Microsoft\\Exchange Server\\.+)\)'
```

agree that it makes no sense for compare script to scan IIS root files, since the only functionality it has is "comparing file hashes", and we don't have known good file hashes for IIS root files
compare script should be deprecated and customers should use mature developed MSERT tools instead (in company with Test-ProxyLogon.ps1): https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download

**Comment by psykokwak4** [comment]
also, attached a version of (should be deprecated) script I think should be used:

1. check all file types
2. no skipping localized files such as *Strings.localized.min.js
  2.1. Note: we are missing localized files for all baselines (as of 03/13/2021), so if you use this version, you'll get tons of NoHashMatch errors for those files
3. Add file SDDL/MODE to result
4. Zip fix
5. also if you are not getting empty files in result csv then that is expected since we have tons of empty files in baseline
6. if you are getting tons of NoHashMatch and those files have exchange version such as `15.X.XXXX.X` in it, then chances are high we don't have their baseline info

[CompareExchangeHashes.txt](https://github.com/microsoft/CSS-Exchange/files/6135121/CompareExchangeHashes.txt)

oh, also feel free to replace the regex used with the pattern shown above (or any other regex format works, also, please remove the file fullpath prefix check) to skip IIS root files

**Comment by psykokwak4** [comment]
closing it since this script is deprecated
