### ISSUE TITLE
Patching and upgrading while the exchange mitigations are in place

### ISSUE THREAD

**Issue by susanTCI** [microsoft/CSS-Exchange#346]
I am going to upgrade and patch my Exchange 2016 tomorrow.  However is it going to be a problem with the mitigations still installed? Or should I rollback the mitigations first then patch and install?   There is no documentation that I was able to find on this scenario.

The first time I attempted to run upgrade from CU11 to CU19 it crashed and all the services were disabled. And all the server component were set to inactive.  I just don't want to run into any problems again.

**Comment by dbacon247** [comment]
Hey @susanTCI 

You should be able to do a CU in place upgrade or SU (security update) in Exchange with services disabled and server component state set to inactive. 

This is a state my Exchange servers are in prior to an in place upgrade as there are several pre configuration steps I do to insure connectivity for all protocols are blocked to the server. For contextual (not instructional) purposes,the pre configuration steps I do prior to an upgrade are:

1) fail over databases and block database activation. 
2) stop transport.
3) set the server component state of server wide offline to inactive. 

With that said, since you had a bad experience and want to avoid this, your best option is to apply only the backend cookie mitigation prior to the CU upgrades across all servers.

The backend cookie mitigation will block the unauthenticated malicious access to your servers while you patch. You will need to re-apply this mitigation after the CU upgrade completes as we found the CU upgrade removes all the web.config settings that are in place for rewrite module. You do not need to re-install the IIS module just re-apply the config. 

With MSI install:
ExchangeMitigations.ps1 -ApplyBackendCookieMitigation -Website "Default Web Site" -FullPathToMSI "full path to msi"

Without MSI install:
ExchangeMitigations.ps1 -ApplyBackendCookieMitigation -Website "Default Web Site"

Once you have completed the SU you can rollback the backend cookie mitigation using as follows: 

ExchangeMitigations.ps1 -RollbackBackendCookieMitigation -Website "Default Web Site"

Your end to end process will look like this: 
1) run the backend cookie mitigation across all servers. 

2) after each CU is complete, re-apply the backend cookie mitigation. 

3) after each SU is complete rollback the backend cookie mitigation. 

For more information on what each mitigation does please visit: https://msrc-blog.microsoft.com/2021/03/05/microsoft-exchange-server-vulnerabilities-mitigations-march-2021/

For more information patching please visit: https://techcommunity.microsoft.com/t5/exchange-team-blog/released-march-2021-exchange-server-security-updates/ba-p/2175901

For more information on the exchange vulnerabilities: https://aka.ms/exchangevulns

If you have any questions feel free to ask. 

Thanks!

**Comment by susanTCI** [comment]
Thanks for your help.  Is that the only mitigation that I have to but back in.

**Comment by dbacon247** [comment]
Hey @susanTCI  the ApplyBackendCookieMitigation  will mitigate only CVE-2021-26855, which is the main vulnerability that allows for unauthenticated access to your Exchange server. We believe ApplyBackendCookieMitigation is sufficient enough on it's own to temporarily mitigate your Exchange server so you can be protected while you patch.

The other mitigations for ECP, OAB, and UM are defense in depth.

**Comment by mark0910** [comment]
I have a question regarding the URL Rewrite mitigation applied to an Exchange Server 2019 with latest CU and SU.

I have been running the Test-ProxyLogon script regularly, along with the CompareExchangeHashes script to spot any activity since I patched my server.  I've tried looking for any comments regarding the CompareExchangeHashes, but have not seen any.

When I run the CompareExchangeHashes script, it does two things that I find odd and false-positive like.

The following is how I'm running it: 

.\CompareExchangeHashes3.29.21.ps1 -CompressSuspiciousAndMissingFilesToCSV $true

NOTE: I rename the script to the date I downloaded it to track any changes, as it's not all that clear to me if this script is being changed regularly for whatever reason by the MS team.

The results are output to to the screen as well as the csv and zip file as expected.
Of note though is that it flags the web.config in the results.csv and copies it to the exchange_version_suspicious folder.
this web.config file only has the URL rewrite modification added to it - so it is like it is flagging the URL rewrite config as the suspicious code.  Why is it doing that?

Once I've applied the latest CU and SU, do I roll back the URL Rewrite mitigation?  Is that mitigation (workaround) replaced by some kind of code fix from the SU install?

Also, the Test-ProxyLogon script - is it supposed to it save the last 30 days of logs to a CVE Log collection folder? I'd expect it to only write a copy of the logs that it found suspicion in.

Thanks,
Mark

**Comment by dbacon247** [comment]
Hi @mark0910 

We no longer support the compare file hashes script and it's since been depreciated/archived.

Recommended guidance today is as follows 

1) Use EOMT to mitigate and scan your unpatched servers for malware. If malware is found there is remediation guidance at https://aka.ms/exchangevulns

2)Once mitigation/scanning and remediation (if necessary) is complete, if your running Exchange 2016/2019 your going to update to the latest CU that was released in March. If your running Exchange 2013, you will need to apply the SU. 

If you applied the SU to Exchange 2016/2019 previously your servers are patched, however, we highly recommend everyone get on the latest CU ASAP so if and when future security updates are applied it's a much easier process. 

3) After the CU and SU are applied, you can roll back the EOMT mitigation.

Once you have the SU or CU applied to your servers there is no need to reapply the mitigation. In fact EOMT will skip the mitigation all together if it detects your on the latest CU or have applied the SU.

You are welcome to run MSERT via EOMT or on your own as you like to insure no malicious activity has persisted after the patch.
