### ISSUE TITLE
EOMT and Test-ProxyLogon for Windows Server 2008 R2 and Exchange 2010 SP3

### ISSUE THREAD

**Issue by ci7alex1** [microsoft/CSS-Exchange#413]
Hi, Any chance of obtatining versions of these scripts that would run on PowerShell 2 for Exchange 2010 with all latest updates? 
According to multiple sources upgrading PowerShell to 3 and newer isn't compatible with Exchange 2010. 

Thanks

**Comment by dbacon247** [comment]
Hey @ci7alex1 

Exchange 2010 isn't vulnerable to the ProxyLogon attack because the Cafe (Client Access Front End) role doesn't exist which is where this vulnerability is. Therefore we aren't planning on including support for Exchange 2010 or PowerShell 2 or any of the older versions of Server past 2008R2 SP1. 

The Microsoft Safety Scanner Tool can be downloaded and executed on its own if you want to look for malicious files on your 2010 Exchange servers, which can be obtained here: https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download

The only vulnerability that impacts Exchange 2010 is https://msrc.microsoft.com/update-guide/vulnerability/CVE-2021-26857

To mitigate CVE-2021-26857 on Exchange 2010, you can disable the unified messaging service/role if it's setup in your Exchange environment. 

To patch Exchange 2010 you download the security update here: https://support.microsoft.com/en-us/topic/description-of-the-security-update-for-microsoft-exchange-server-2010-service-pack-3-march-2-2021-kb5000978-894f27bf-281e-44f8-b9ba-dad705534459

For more information on the Exchange vulnerabilities, mitigation, remediation, and patching please visit https://aka.ms/exchangevulns
