### ISSUE TITLE
HAFNIUM targeting Exchange Servers with 0-day exploits

### ISSUE THREAD

**Issue by jonsmith40** [microsoft/CSS-Exchange#495]
The information being published for searching logs is incorrect. The blog makes the assumption that Exchange is in stall on C.
$env:PROGRAMFILES is incorrect. This always references c:\Program Files. and should be corrected to $env:exchangeinstallpath. 
It is highly unlikely that Exchange Administrators would deploy Exchange to C:

**Comment by bill-long** [comment]
The above PR is unrelated to this issue. We just combined histories between a couple of repos so we will get some of these incorrect links.

In regards to this particular issue, the Test-ProxyLogon script reads the Exchange location from the registry and searches there. So I guess this issue is referring to the blog post here: https://www.microsoft.com/security/blog/2021/03/02/hafnium-targeting-exchange-servers/

I've raised this to the owners of that content.
