### ISSUE TITLE
False possitives about Download Domains when no OWA Virtual Directory exists

### ISSUE THREAD

**Issue by Niehweune** [microsoft/CSS-Exchange#787]
https://github.com/microsoft/CSS-Exchange/blob/e15e04bbc118ca9bb1215858d28e0c38c5133168/Diagnostics/HealthChecker/Analyzer/Security/Invoke-AnalyzerSecurityCve-2021-1730.ps1#L33

The Healthreport shows an error when EnableDownloadDomains is set to $false. However, in a hybrid setup where the onprem server(s) only serve as management servers and/or transport servers and there's no OWAVirtualDirectory, this is a false positive.

This script should therefor check if there's an OWA Virtual Directory and if there's no OWA confgured, this shouldn't show an error.

Furthermore, of only an internal OWA url is configured (external URL -eq $null), the External Download hostname can be null as well (since that means there's no external access to OWA anyway)

**Comment by dpaulson45** [comment]
The Hybrid servers are Exchange servers and should have OWA Virtual Directory. Therefore it isn't a false positive if it isn't configured.

**Comment by Niehweune** [comment]
Fair point, let me rephrase that:

Let's say you have a scenario where all mailboxes are cloud-based, but you still need an onprem Exchange server for either legacy SMTP applications, or for the purpose of management (in case you use ADFS or AADConnect).

In that case, as a security best practice, OWA should be made unavailable on the onprem Exchange (since it serves no purpose at all). To do this, one of the steps (besides DNS & firewall/load balancer/... changes), is to null the external (and internal) URLs on the OWAVirtualDirectory.

However, when you do that, this script will start complaining about it, either because Download Domains is disabled (granted, that may also be because a less security-minded admin just hasn't configured it), or one or both URLs is $null.

I'm currently advising my clients to configure 'localhost' as downoaddomain on the virtual directory in this case, so the alert goes away (but that's more of a hack instead of a clean solution IMHO).

**Comment by dpaulson45** [comment]
The problem is going to be to determine that is how you use the server. We 'could' check to see if there are any mailboxes on the server, but what if it is just a DR server at the moment you run the script. What if you have some mailboxes on the server and they are just test mailbox or admin mailboxes that aren't used for actual mail use.

For the External domain, some customers don't set the external URL for multiple reasons. But they still use the internal URL, at that point they are still subject to the security vulnerability.

I have never seen the internal URL set to NULL for the OWAVirtualDirectory. With it being NULL, I would still suspect that you can hit the server's OWA virtual directory by the FQDN. If you have those test mailboxes on the server, they should still be able to log in and you still have the vulnerability. 

For all of this, I am just following the CVE to what it provides and what the code provides to 'enable' this security feature to avoid the vulnerability. It is up to you and your team to decide if this vulnerability is a concern to you with how you use the Exchange Server.
