### ISSUE TITLE
[Update] Credential Guard Warning

### ISSUE THREAD

**Issue by GregLeonard** [microsoft/CSS-Exchange#908]
The Detection of Credential Guard being enabled on Exchange servers states in the description that this is "Not Supported".  As Msft does not have a formal externally referenceable site stating this, should this be updated to "Not Recommended"?  

There are multiple reports of this causing issues with Exchange for customers, but without a corresponding external support statement indicating this is 'not supported', should this be referred to as "Not Recommended".

Best Regards,
Greg Leonard
[Msft FTE]

**Comment by dpaulson45** [comment]
It is not supported. We don't have any formal external reference stating any of the things that are not supported. If it isn't stated that we supported customers are typically on their own. 

We have had a few cases where the performance of the servers is greatly impacted when Credential Guard is installed. The official word back that we got back from PG on this was that we, Exchange PG, does not support it at this time. 

Also don't want to change the wording from "Not Supported" to "Not Recommended" due to the customers and engineers not be willing to address as quickly. 

@bill-long anything else that I am missing?

**Comment by bill-long** [comment]
@dpaulson45 Not missing anything. Credential Guard is not supported on Exchange Server. That fact is documented internally in the issues that were filed when these performance problems were escalated.

**Comment by dpaulson45** [comment]
@GregLeonard let us know if you have any more questions regarding this, otherwise, I will close out the issue.

**Comment by dpaulson45** [comment]
question answered, closing issue.
